language: ruby
rvm:
  - 2.3.1

notifications:
  slack:
    rooms:
      secure: "wPQW78gt6BIMbtJw16F/1sHpWsOA37UJqGiqdI1i9qpwOgXRSABGpviRKZQ/eAVEFx3BFrFLzNFrtIwoE2t+M1rxaQFn5lVWnJwJIfZiCz9Rcqb3R24sc8X8usPKPERAaDCPBEK4XGgXac04CNRm/iEfdEwLzZxk3+It64YLnFFHhlinghoZ6rJI6IBjm5GraDLKS3Ma80bBV8YbsWLszkrd7u1yhpTA4Kti+yeKim+1wjs64SQq5YsBe5xyPEry5KEGSC6CYacx2JzbH3soTPDr7ABUgi5MUIfhMOuO7lCTifk95uidwVAVysYdC6WYWyV3vgkvdMGiVKhGM8RM3upGnUeIHaK7gxbKiS2GeaO1MHGPYLFa66QVn8pBYepl53NXH1MuFE0BbFp9UTeK7TeEyqrch2lx2FEacMZ4jv8EVANbvxfONDeVRyPJh06lX+RS0weasyNymyO9hfRiBuaAhMREttFbQwme+mY/CW5qIkb5Y7pS9pYn7l95Jzk9xbSpYunWfRXw+ZXBlu+I3GM7oRowgPiH3PuarkJTLCYec9J1LAWlSls98GbyPejHgXiz5i/je4TD+SInKQFeQTn9P6iHVFt+/Tt4Dr47bQKs+owuVgvE7rpcgs6UtYEiPYps1i5pcG6iOeKNgiHVRSFlgqT2z2TUhTi+QpnYTAo="

